// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Title field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Service Detail Page → Gallery*
 */
export interface ServiceDetailPageDocumentDataGalleryItem {
  /**
   * gallery_item field in *Service Detail Page → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.gallery[].gallery_item
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gallery_item: prismic.ImageField<never>;
}

/**
 * Item in *Service Detail Page → testimonials*
 */
export interface ServiceDetailPageDocumentDataTestimonialsItem {
  /**
   * client name field in *Service Detail Page → testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.testimonials[].client_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  client_name: prismic.RichTextField;

  /**
   * testimonial_text field in *Service Detail Page → testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.testimonials[].testimonial_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testimonial_text: prismic.RichTextField;
}

type ServiceDetailPageDocumentDataSlicesSlice =
  | ServiceContentSectionSlice
  | ServiceCallToActionSlice
  | FrequentlyAskedQuestionsSlice;

/**
 * Content for Service Detail Page documents
 */
interface ServiceDetailPageDocumentData {
  /**
   * service_title field in *Service Detail Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.service_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_title: prismic.RichTextField;

  /**
   * hero_image field in *Service Detail Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * introduction field in *Service Detail Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  introduction: prismic.RichTextField;

  /**
   * service_details field in *Service Detail Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.service_details
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_details: prismic.RichTextField;

  /**
   * Gallery field in *Service Detail Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<
    Simplify<ServiceDetailPageDocumentDataGalleryItem>
  >;

  /**
   * testimonials field in *Service Detail Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.testimonials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<ServiceDetailPageDocumentDataTestimonialsItem>
  >;

  /**
   * Slice Zone field in *Service Detail Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServiceDetailPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Service Detail Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service Detail Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service Detail Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_page.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Service Detail Page document from Prismic
 *
 * - **API ID**: `service_detail_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDetailPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDetailPageDocumentData>,
    "service_detail_page",
    Lang
  >;

/**
 * Item in *Services Page → Services List*
 */
export interface ServicesPageDocumentDataServicesListItem {
  /**
   * service_title field in *Services Page → Services List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.services_list[].service_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_title: prismic.RichTextField;

  /**
   * service_description field in *Services Page → Services List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.services_list[].service_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_description: prismic.RichTextField;

  /**
   * service_image field in *Services Page → Services List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.services_list[].service_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  service_image: prismic.ImageField<never>;

  /**
   * service_link field in *Services Page → Services List*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.services_list[].service_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service_link: prismic.LinkField;
}

type ServicesPageDocumentDataSlicesSlice = never;

/**
 * Content for Services Page documents
 */
interface ServicesPageDocumentData {
  /**
   * page_title field in *Services Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_title: prismic.RichTextField;

  /**
   * introduction field in *Services Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  introduction: prismic.RichTextField;

  /**
   * Services List field in *Services Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.services_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services_list: prismic.GroupField<
    Simplify<ServicesPageDocumentDataServicesListItem>
  >;

  /**
   * Slice Zone field in *Services Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.meta_title
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.meta_description
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.meta_image
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Services Page document from Prismic
 *
 * - **API ID**: `services_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesPageDocumentData>,
    "services_page",
    Lang
  >;

export type AllDocumentTypes =
  | HomeDocument
  | ServiceDetailPageDocument
  | ServicesPageDocument;

/**
 * Item in *FrequentlyAskedQuestions → Default → Primary → FAQ's*
 */
export interface FrequentlyAskedQuestionsSliceDefaultPrimaryFaqsItem {
  /**
   * Question field in *FrequentlyAskedQuestions → Default → Primary → FAQ's*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.default.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *FrequentlyAskedQuestions → Default → Primary → FAQ's*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.default.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *FrequentlyAskedQuestions → Default → Primary*
 */
export interface FrequentlyAskedQuestionsSliceDefaultPrimary {
  /**
   * Section Title field in *FrequentlyAskedQuestions → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.RichTextField;

  /**
   * FAQ's field in *FrequentlyAskedQuestions → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<
    Simplify<FrequentlyAskedQuestionsSliceDefaultPrimaryFaqsItem>
  >;
}

/**
 * Default variation for FrequentlyAskedQuestions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrequentlyAskedQuestionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FrequentlyAskedQuestionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FrequentlyAskedQuestions*
 */
type FrequentlyAskedQuestionsSliceVariation =
  FrequentlyAskedQuestionsSliceDefault;

/**
 * FrequentlyAskedQuestions Shared Slice
 *
 * - **API ID**: `frequently_asked_questions`
 * - **Description**: FrequentlyAskedQuestions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrequentlyAskedQuestionsSlice = prismic.SharedSlice<
  "frequently_asked_questions",
  FrequentlyAskedQuestionsSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hero Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ServiceCallToAction → Default → Primary*
 */
export interface ServiceCallToActionSliceDefaultPrimary {
  /**
   * Headline field in *ServiceCallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_call_to_action.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * subheadline field in *ServiceCallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Supporting text or a brief description
   * - **API ID Path**: service_call_to_action.default.primary.subheadline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheadline: prismic.RichTextField;

  /**
   * Phone field in *ServiceCallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_call_to_action.default.primary.phone_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * Email field in *ServiceCallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_call_to_action.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Link field in *ServiceCallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: To contact page
   * - **API ID Path**: service_call_to_action.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Alignment field in *ServiceCallToAction → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: service_call_to_action.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  alignment: prismic.SelectField<"Left" | "Right" | "Center">;

  /**
   * Background Image field in *ServiceCallToAction → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_call_to_action.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Color field in *ServiceCallToAction → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: service_call_to_action.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;
}

/**
 * Default variation for ServiceCallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceCallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceCallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceCallToAction*
 */
type ServiceCallToActionSliceVariation = ServiceCallToActionSliceDefault;

/**
 * ServiceCallToAction Shared Slice
 *
 * - **API ID**: `service_call_to_action`
 * - **Description**: ServiceCallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceCallToActionSlice = prismic.SharedSlice<
  "service_call_to_action",
  ServiceCallToActionSliceVariation
>;

/**
 * Primary content in *ServiceContentSection → Default → Primary*
 */
export interface ServiceContentSectionSliceDefaultPrimary {
  /**
   * Section Title field in *ServiceContentSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.RichTextField;

  /**
   * Section Content field in *ServiceContentSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.default.primary.section_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_content: prismic.RichTextField;

  /**
   * SectionImage field in *ServiceContentSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.default.primary.sectionimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  sectionimage: prismic.ImageField<never>;
}

/**
 * Default variation for ServiceContentSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceContentSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceContentSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ServiceContentSection → Dark Background → Primary*
 */
export interface ServiceContentSectionSliceDarkBackgroundPrimary {
  /**
   * Section Title field in *ServiceContentSection → Dark Background → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.darkBackground.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.RichTextField;

  /**
   * Section Content field in *ServiceContentSection → Dark Background → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.darkBackground.primary.section_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_content: prismic.RichTextField;

  /**
   * SectionImage field in *ServiceContentSection → Dark Background → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.darkBackground.primary.sectionimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  sectionimage: prismic.ImageField<never>;
}

/**
 * Dark Background variation for ServiceContentSection Slice
 *
 * - **API ID**: `darkBackground`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceContentSectionSliceDarkBackground =
  prismic.SharedSliceVariation<
    "darkBackground",
    Simplify<ServiceContentSectionSliceDarkBackgroundPrimary>,
    never
  >;

/**
 * Primary content in *ServiceContentSection → Image left - Dark → Primary*
 */
export interface ServiceContentSectionSliceImageLeftDarkPrimary {
  /**
   * Section Title field in *ServiceContentSection → Image left - Dark → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.imageLeftDark.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.RichTextField;

  /**
   * Section Content field in *ServiceContentSection → Image left - Dark → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.imageLeftDark.primary.section_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_content: prismic.RichTextField;

  /**
   * SectionImage field in *ServiceContentSection → Image left - Dark → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.imageLeftDark.primary.sectionimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  sectionimage: prismic.ImageField<never>;
}

/**
 * Image left - Dark variation for ServiceContentSection Slice
 *
 * - **API ID**: `imageLeftDark`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceContentSectionSliceImageLeftDark =
  prismic.SharedSliceVariation<
    "imageLeftDark",
    Simplify<ServiceContentSectionSliceImageLeftDarkPrimary>,
    never
  >;

/**
 * Primary content in *ServiceContentSection → Image Right - Light → Primary*
 */
export interface ServiceContentSectionSliceImageRightLightPrimary {
  /**
   * Section Title field in *ServiceContentSection → Image Right - Light → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.imageRightLight.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.RichTextField;

  /**
   * Section Content field in *ServiceContentSection → Image Right - Light → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.imageRightLight.primary.section_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_content: prismic.RichTextField;

  /**
   * SectionImage field in *ServiceContentSection → Image Right - Light → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_content_section.imageRightLight.primary.sectionimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  sectionimage: prismic.ImageField<never>;
}

/**
 * Image Right - Light variation for ServiceContentSection Slice
 *
 * - **API ID**: `imageRightLight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceContentSectionSliceImageRightLight =
  prismic.SharedSliceVariation<
    "imageRightLight",
    Simplify<ServiceContentSectionSliceImageRightLightPrimary>,
    never
  >;

/**
 * Slice variation for *ServiceContentSection*
 */
type ServiceContentSectionSliceVariation =
  | ServiceContentSectionSliceDefault
  | ServiceContentSectionSliceDarkBackground
  | ServiceContentSectionSliceImageLeftDark
  | ServiceContentSectionSliceImageRightLight;

/**
 * ServiceContentSection Shared Slice
 *
 * - **API ID**: `service_content_section`
 * - **Description**: ServiceContentSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceContentSectionSlice = prismic.SharedSlice<
  "service_content_section",
  ServiceContentSectionSliceVariation
>;

/**
 * Item in *ServicesOverview → Default → Primary → Services*
 */
export interface ServicesOverviewSliceDefaultPrimaryServicesItem {
  /**
   * service_title field in *ServicesOverview → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.default.primary.services[].service_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_title: prismic.RichTextField;

  /**
   * Service Description field in *ServicesOverview → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.default.primary.services[].service_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_description: prismic.RichTextField;

  /**
   * Service Image field in *ServicesOverview → Default → Primary → Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.default.primary.services[].service_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  service_image: prismic.ImageField<never>;

  /**
   * Service Link field in *ServicesOverview → Default → Primary → Services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.default.primary.services[].service_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service_link: prismic.LinkField;
}

/**
 * Primary content in *ServicesOverview → Default → Primary*
 */
export interface ServicesOverviewSliceDefaultPrimary {
  /**
   * Section Title field in *ServicesOverview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.RichTextField;

  /**
   * Services field in *ServicesOverview → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<
    Simplify<ServicesOverviewSliceDefaultPrimaryServicesItem>
  >;
}

/**
 * Default variation for ServicesOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesOverview*
 */
type ServicesOverviewSliceVariation = ServicesOverviewSliceDefault;

/**
 * ServicesOverview Shared Slice
 *
 * - **API ID**: `services_overview`
 * - **Description**: ServicesOverview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesOverviewSlice = prismic.SharedSlice<
  "services_overview",
  ServicesOverviewSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ServiceDetailPageDocument,
      ServiceDetailPageDocumentData,
      ServiceDetailPageDocumentDataGalleryItem,
      ServiceDetailPageDocumentDataTestimonialsItem,
      ServiceDetailPageDocumentDataSlicesSlice,
      ServicesPageDocument,
      ServicesPageDocumentData,
      ServicesPageDocumentDataServicesListItem,
      ServicesPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      FrequentlyAskedQuestionsSlice,
      FrequentlyAskedQuestionsSliceDefaultPrimaryFaqsItem,
      FrequentlyAskedQuestionsSliceDefaultPrimary,
      FrequentlyAskedQuestionsSliceVariation,
      FrequentlyAskedQuestionsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ServiceCallToActionSlice,
      ServiceCallToActionSliceDefaultPrimary,
      ServiceCallToActionSliceVariation,
      ServiceCallToActionSliceDefault,
      ServiceContentSectionSlice,
      ServiceContentSectionSliceDefaultPrimary,
      ServiceContentSectionSliceDarkBackgroundPrimary,
      ServiceContentSectionSliceImageLeftDarkPrimary,
      ServiceContentSectionSliceImageRightLightPrimary,
      ServiceContentSectionSliceVariation,
      ServiceContentSectionSliceDefault,
      ServiceContentSectionSliceDarkBackground,
      ServiceContentSectionSliceImageLeftDark,
      ServiceContentSectionSliceImageRightLight,
      ServicesOverviewSlice,
      ServicesOverviewSliceDefaultPrimaryServicesItem,
      ServicesOverviewSliceDefaultPrimary,
      ServicesOverviewSliceVariation,
      ServicesOverviewSliceDefault,
    };
  }
}
