// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  frequently_asked_questions: dynamic(
    () => import("./FrequentlyAskedQuestions"),
  ),
  hero: dynamic(() => import("./Hero")),
  service_call_to_action: dynamic(() => import("./ServiceCallToAction")),
  service_content_section: dynamic(() => import("./ServiceContentSection")),
  services_overview: dynamic(() => import("./ServicesOverview")),
};
